# URL = 'https://www.tripadvisor.co.kr/Attractions-g294211-Activities-a_allAttractions.true-China.html'
# URL = 'https://www.tripadvisor.co.kr/Attractions-g308272-Activities-c49-t161-Shanghai.html'
# URL = 'https://www.tripadvisor.co.kr/Attractions-g308272-Activities-c47-t163-Shanghai.html'
URL = 'https://www.tripadvisor.co.kr/Attractions-g308272-Activities-c26-t143-Shanghai.html'
ALL_BTN = 'a.BMQDV._F.Gv.wSSLS.SwZTJ.FGwzt.ukgoS'
CARD_SELECTOR = 'div.alPVI.eNNhq.PgLKC.tnGGX'
REVIEW_NEXT_BTN = 'a.BrOJk.u.j.z._F.wSSLS.tIqAi.unMkR'
REVIEW_NEXT_XPATH = '/html/body/div[1]/main/div[1]/div[2]/div[2]/div[2]/div/div[1]/section[7]/div/div/div/section/section/div[1]/div/div[5]/div/div[11]/div[1]/div/div[1]/div[2]/div/a[@aria-label="Next page"]'
CARD_NEXT_XPATH = '//*[@id="lithium-root"]/main/div[1]/div/div/div[3]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/section[40]/div/div[1]/div/div[1]/div[2]/div/a[@aria-label="Next page"]'
REVIEW_DETAIL_XPATH = '/html/body/div[1]/main/div[1]/div[2]/div[2]/div[2]/div/div[1]/section[7]/div/div/div/section/section/div[1]/div/div[5]/div/div[1]/div/div/*/span[@class="yCeTE"]'
REVIEWS_XPATH = '/html/body/div[1]/main/div[1]/div[2]/div[2]/div[2]/div/div[1]/section[7]/div/div/div/section/section/div[1]/div/div[5]/div/div[@data-automation="tab"]'
CARDS_XPATH = '/html/body/div[1]/main/div[1]/div/div/div[3]/div/div[2]/div[2]/div[2]/div/div/div[2]/div/div[2]/div/div/section[@data-automation="WebPresentation_SingleFlexCardSection"]/div/div/div/div/article/div[2]/header/div/div/div'

